source: src
collections_config:
  layouts:
    path: _includes/
    output: false
    url:
    filter:
      base: all
      include:
        - '*.liquid'
      exclude:
    parse_branch_index:
    name: Layouts
    description: ''
    icon: document_scanner
    documentation:
    preview:
    sort:
    sort_options:
    singular_name:
    singular_key:
    _editables: {}
    _enabled_editors:
      - data
    _inputs: {}
    _select_data: {}
    _structures: {}
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas: {}
    schema_key:
_inputs:
  layout:
    type: auto
    hidden: true
    cascade: true
  eleventyExcludeFromCollections:
    type: auto
    hidden: true
    cascade: true
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
timezone: Etc/UTC
